# Importing necessary libraries

In [1]:
# pandas
import pandas as pd

# numpy, matplotlib, seaborn
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Machine learning
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor

# GridSearchCV to find optimal min_samples_split
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn import preprocessing
from sklearn.feature_selection import RFE

# Importing train-test-split 
from sklearn.model_selection import train_test_split

# Evaluation metrics
from sklearn.metrics import *

# Ignoring warning
import sys
import warnings

if not sys.warnoptions:
    warnings.simplefilter("ignore")

# Importing the data

In [2]:
df=pd.read_csv('hour.csv',index_col=0)
df.head()

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,,
1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

In [3]:
df.drop(columns=['dteday','yr','casual','registered'],axis=1,inplace=True)
df.head()

,season,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
instant,,,,,,,,,,,,
1,1,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,16
2,1,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,40
3,1,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,32
4,1,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,13
5,1,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,1

# Model building

In [4]:
df.dtypes

season          int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
cnt             int64
dtype: object

In [5]:
df_objects=['season','mnth','hr','holiday','weekday','workingday','weathersit']
for i in df_objects:
    df[i]=df[i].apply(lambda x:str(x))

In [6]:
df.dtypes

season         object
mnth           object
hr             object
holiday        object
weekday        object
workingday     object
weathersit     object
temp          float64
atemp         float64
hum           float64
windspeed     float64
cnt             int64
dtype: object

# Building base model

In [7]:
def model(model_name,X,Y):
    x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=123)
    model_name.fit(x_train,y_train)
    y_pred=model_name.predict(x_test)
    mse=mean_squared_error(y_test,y_pred)
    
    print('The rmse score for the model=',np.sqrt(mse))
    print('---------------------------------------')
    print('The r^2 value for the model=',r2_score(y_test,y_pred))

In [8]:
df1=df.copy()

In [9]:
x=df1.drop('cnt',axis=1)
y=df1['cnt']

In [10]:
model(LinearRegression(),x,y)

The rmse score for the model= 150.28181522182192
---------------------------------------
The r^2 value for the model= 0.32399854121719174

In [11]:
model(RandomForestRegressor(),x,y)

The rmse score for the model= 70.85078352596707
---------------------------------------
The r^2 value for the model= 0.8497466777115262

In [12]:
model(DecisionTreeRegressor(),x,y)

The rmse score for the model= 92.43828299062821
---------------------------------------
The r^2 value for the model= 0.744236533925386

In [13]:
import statsmodels.formula.api as smf
import statsmodels.api as sm

In [14]:
data=pd.get_dummies(df1,drop_first=True)
data.head()

,temp,atemp,hum,windspeed,cnt,season_2,season_3,season_4,mnth_10,mnth_11,...,weekday_1,weekday_2,weekday_3,weekday_4,weekday_5,weekday_6,workingday_1,weathersit_2,weathersit_3,weathersit_4
instant,,,,,,,,,,,,,,,,,,,,,
1,0.24,0.2879,0.81,0.0,16,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0.22,0.2727,0.80,0.0,40,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0.22,0.2727,0.80,0.0,32,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0.24,0.2879,0.75,0.0,13,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
5,0.24,0.2879,0.75,0.0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [15]:
x1=data.drop('cnt',axis=1)
y1=data['cnt']

In [16]:
data.columns

Index(['temp', 'atemp', 'hum', 'windspeed', 'cnt', 'season_2', 'season_3',
       'season_4', 'mnth_10', 'mnth_11', 'mnth_12', 'mnth_2', 'mnth_3',
       'mnth_4', 'mnth_5', 'mnth_6', 'mnth_7', 'mnth_8', 'mnth_9', 'hr_1',
       'hr_10', 'hr_11', 'hr_12', 'hr_13', 'hr_14', 'hr_15', 'hr_16', 'hr_17',
       'hr_18', 'hr_19', 'hr_2', 'hr_20', 'hr_21', 'hr_22', 'hr_23', 'hr_3',
       'hr_4', 'hr_5', 'hr_6', 'hr_7', 'hr_8', 'hr_9', 'holiday_1',
       'weekday_1', 'weekday_2', 'weekday_3', 'weekday_4', 'weekday_5',
       'weekday_6', 'workingday_1', 'weathersit_2', 'weathersit_3',
       'weathersit_4'],
      dtype='object')

In [17]:
m1 = sm.OLS(y1,sm.add_constant(x1),family=sm.families.Gaussian())
model1 = m1.fit()
model1.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                  Results: Ordinary least squares
====================================================================
Model:              OLS              Adj. R-squared:     0.631
Dependent Variable: cnt              AIC:                212799.7616
Date:               2019-05-27 17:35 BIC:                213203.4385
No. Observations:   17379            Log-Likelihood:     -1.0635e+05
Df Model:           51               F-statistic:        584.2
Df Residuals:       17327            Prob (F-statistic): 0.00
R-squared:          0.632            Scale:              12134.
--------------------------------------------------------------------
                Coef.   Std.Err.    t     P>|t|    [0.025    0.975]
--------------------------------------------------------------------
const          -27.4742   7.0955  -3.8721 0.0001  -41.3821  -13.5663
temp           195.1921  31.9175   6.1155 0.0000  132.6305  257.7537
atemp          103.9531  33.1547   3.1354 0.0017   38.9666  168.9397
hum           -114.9024   5.9797 -19.2155 0.0000 -126.6232 -103.1817
windspeed      -43.2351   7.6305  -5.6661 0.0000  -58.1916  -28.2787
season_2        39.4906   5.2578   7.5109 0.0000   29.1847   49.7964
season_3        28.8578   6.2248   4.6359 0.0000   16.6565   41.0590
season_4        66.0479   5.2858  12.4953 0.0000   55.6871   76.4086
mnth_10          3.9416   7.0161   0.5618 0.5743   -9.8106   17.6939
mnth_11        -15.5826   6.7536  -2.3073 0.0210  -28.8203   -2.3449
mnth_12         -9.3163   5.3638  -1.7369 0.0824  -19.8298    1.1972
mnth_2          -0.4609   4.2442  -0.1086 0.9135   -8.7799    7.8582
mnth_3           4.4203   4.7679   0.9271 0.3539   -4.9252   13.7658
mnth_4          -9.1995   7.0836  -1.2987 0.1941  -23.0841    4.6850
mnth_5           0.5152   7.5761   0.0680 0.9458  -14.3347   15.3651
mnth_6         -20.7340   7.7826  -2.6641 0.0077  -35.9887   -5.4793
mnth_7         -40.7689   8.7337  -4.6680 0.0000  -57.8878  -23.6500
mnth_8         -15.6046   8.5184  -1.8319 0.0670  -32.3015    1.0923
mnth_9          15.5058   7.5733   2.0474 0.0406    0.6615   30.3502
hr_1           -16.4977   5.7874  -2.8506 0.0044  -27.8416   -5.1537
hr_10          104.2107   5.8133  17.9262 0.0000   92.8160  115.6054
hr_11          127.0021   5.8555  21.6892 0.0000  115.5246  138.4796
hr_12          164.1738   5.9046  27.8043 0.0000  152.6001  175.7474
hr_13          157.7321   5.9447  26.5334 0.0000  146.0800  169.3843
hr_14          141.0138   5.9777  23.5901 0.0000  129.2970  152.7306
hr_15          150.1886   5.9891  25.0769 0.0000  138.4493  161.9279
hr_16          212.6712   5.9768  35.5829 0.0000  200.9561  224.3863
hr_17          367.4906   5.9425  61.8410 0.0000  355.8427  379.1385
hr_18          337.0098   5.9042  57.0798 0.0000  325.4370  348.5826
hr_19          230.4248   5.8499  39.3898 0.0000  218.9585  241.8911
hr_2           -24.4135   5.8076  -4.2037 0.0000  -35.7970  -13.0300
hr_20          152.5053   5.8186  26.2100 0.0000  141.1003  163.9103
hr_21          104.5791   5.7953  18.0454 0.0000   93.2196  115.9385
hr_22           68.8433   5.7847  11.9010 0.0000   57.5048   80.1818
hr_23           30.9933   5.7800   5.3621 0.0000   19.6638   42.3227
hr_3           -34.3153   5.8494  -5.8665 0.0000  -45.7807  -22.8499
hr_4           -36.0087   5.8549  -6.1501 0.0000  -47.4849  -24.5324
hr_5           -19.7552   5.8171  -3.3961 0.0007  -31.1573   -8.3531
hr_6            38.7841   5.8019   6.6847 0.0000   27.4118   50.1564
hr_7           172.8931   5.7906  29.8575 0.0000  161.5429  184.2433
hr_8           311.6446   5.7839  53.8818 0.0000  300.3077  322.9816
hr_9           161.5087   5.7898  27.8953 0.0000  150.1600  172.8573
holiday_1      -14.5715   4.7110  -3.0931 0.0020  -23.8055   -5.3375
weekday_1       -3.7475   2.1041  -1.7811 0.0749   -7.8717    0.3767
weekday_2       -2.5303   2.2768  -1.1113 0.2664   -6.9930    1.9325
weekday_3        0.4949   2.2725   0.2178 0.8276   -3.9595    4.9492
weekday_4       -0.8021   2.2544  -0.3558 0.7220   -5.2210    3.6169
weekday_5        3.8286   2.2512   1.7007 0.0890   -0.5841    8.2413
weekday_6       14.7269   3.1158   4.7265 0.0000    8.6196   20.8342
workingday_1    11.8151   1.9551   6.0433 0.0000    7.9829   15.6472
weathersit_2    -6.3713   2.0774  -3.0669 0.0022  -10.4433   -2.2994
weathersit_3   -60.3711   3.5025 -17.2365 0.0000  -67.2363  -53.5058
weathersit_4   -33.1693  63.7637  -0.5202 0.6029 -158.1525   91.8139
--------------------------------------------------------------------
Omnibus:          1809.005    Durbin-Watson:       0.433
Prob(Omnibus):    0.000       Jarque-Bera (JB):    3761.709
Skew:             0.665       Prob(JB):            0.000
Kurtosis:         4.850       Condition No.:       14323823030256348
====================================================================
* The condition number is large (1e+16). This might indicate
strong multicollinearity or other numerical problems.
"""

In [18]:
#Removing variables that are insignificant i,e removing variables which have p value >0.05
x2=x1.drop(['mnth_10','mnth_12','mnth_2','mnth_3','mnth_4','mnth_5','mnth_8','mnth_9','weekday_1','weekday_2','weekday_3','weekday_4','weekday_5','weathersit_4'],axis=1)

In [19]:
m2 = sm.OLS(y1,sm.add_constant(x2),family=sm.families.Gaussian())
model2 = m2.fit()
model2.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                  Results: Ordinary least squares
====================================================================
Model:              OLS              Adj. R-squared:     0.630
Dependent Variable: cnt              AIC:                212858.7973
Date:               2019-05-27 17:35 BIC:                213161.5550
No. Observations:   17379            Log-Likelihood:     -1.0639e+05
Df Model:           38               F-statistic:        778.6
Df Residuals:       17340            Prob (F-statistic): 0.00
R-squared:          0.630            Scale:              12185.
--------------------------------------------------------------------
                 Coef.   Std.Err.    t     P>|t|    [0.025   0.975]
--------------------------------------------------------------------
const           -31.6897   6.7327  -4.7068 0.0000  -44.8866 -18.4929
temp            200.9236  30.5736   6.5718 0.0000  140.9963 260.8509
atemp           104.7610  32.8104   3.1929 0.0014   40.4494 169.0726
hum            -111.2083   5.8918 -18.8752 0.0000 -122.7568 -99.6598
windspeed       -43.5023   7.5930  -5.7292 0.0000  -58.3854 -28.6191
season_2         35.1906   3.0797  11.4266 0.0000   29.1541  41.2272
season_3         23.8376   4.0566   5.8762 0.0000   15.8863  31.7890
season_4         65.8857   3.0263  21.7707 0.0000   59.9538  71.8177
mnth_11         -15.6438   3.6701  -4.2624 0.0000  -22.8376  -8.4499
mnth_6          -18.3075   3.4195  -5.3538 0.0000  -25.0101 -11.6049
mnth_7          -38.4820   3.6416 -10.5673 0.0000  -45.6200 -31.3441
hr_1            -16.5655   5.7987  -2.8568 0.0043  -27.9314  -5.1995
hr_10           104.2724   5.8225  17.9084 0.0000   92.8597 115.6852
hr_11           127.0895   5.8597  21.6886 0.0000  115.6038 138.5752
hr_12           164.2722   5.9027  27.8301 0.0000  152.7024 175.8421
hr_13           157.8293   5.9365  26.5862 0.0000  146.1931 169.4654
hr_14           141.0989   5.9645  23.6566 0.0000  129.4079 152.7898
hr_15           150.2669   5.9737  25.1546 0.0000  138.5577 161.9760
hr_16           212.7086   5.9611  35.6830 0.0000  201.0243 224.3929
hr_17           367.5727   5.9331  61.9528 0.0000  355.9432 379.2022
hr_18           337.0652   5.8997  57.1327 0.0000  325.5012 348.6292
hr_19           230.4971   5.8528  39.3823 0.0000  219.0250 241.9692
hr_2            -24.4443   5.8191  -4.2007 0.0000  -35.8503 -13.0383
hr_20           152.5611   5.8256  26.1880 0.0000  141.1423 163.9799
hr_21           104.6092   5.8050  18.0204 0.0000   93.2307 115.9877
hr_22            68.8631   5.7957  11.8817 0.0000   57.5029  80.2234
hr_23            30.9964   5.7918   5.3518 0.0000   19.6440  42.3489
hr_3            -34.2914   5.8599  -5.8519 0.0000  -45.7774 -22.8054
hr_4            -36.0508   5.8647  -6.1471 0.0000  -47.5462 -24.5555
hr_5            -19.7455   5.8259  -3.3893 0.0007  -31.1648  -8.3262
hr_6             38.8144   5.8103   6.6802 0.0000   27.4256  50.2033
hr_7            172.9105   5.8002  29.8110 0.0000  161.5415 184.2795
hr_8            311.6706   5.7952  53.7809 0.0000  300.3114 323.0297
hr_9            161.5535   5.8016  27.8465 0.0000  150.1818 172.9252
holiday_1       -16.3362   5.4359  -3.0052 0.0027  -26.9910  -5.6813
weekday_6        14.7549   3.1207   4.7280 0.0000    8.6380  20.8719
workingday_1     11.0932   2.4364   4.5530 0.0000    6.3175  15.8688
weathersit_2     -6.4871   2.0756  -3.1254 0.0018  -10.5556  -2.4187
weathersit_3    -60.2725   3.5008 -17.2169 0.0000  -67.1344 -53.4106
--------------------------------------------------------------------
Omnibus:             1860.341       Durbin-Watson:          0.431
Prob(Omnibus):       0.000          Jarque-Bera (JB):       3923.710
Skew:                0.677          Prob(JB):               0.000
Kurtosis:            4.894          Condition No.:          89
====================================================================

"""

In [20]:
def vif_cal(input_data, dependent_col):
    vif_df = pd.DataFrame( columns = ['Var', 'Vif'])
    x_vars=input_data
    xvar_names=x_vars.columns
    for i in range(0,xvar_names.shape[0]):
        y=x_vars[xvar_names[i]] 
        x=x_vars[xvar_names.drop(xvar_names[i])]
        rsq=sm.OLS(y,x).fit().rsquared  
        vif=round(1/(1-rsq),2)
        vif_df.loc[i] = [xvar_names[i], vif]
    return vif_df.sort_values(by = 'Vif', axis=0, ascending=False, inplace=False)

In [21]:
vif_cal(x2,y1)

             Var     Vif
1          atemp  380.54
0           temp  375.48
2            hum   14.93
3      windspeed    3.68
33     holiday_1    0.58
18         hr_17    0.50
17         hr_16    0.50
16         hr_15    0.50
15         hr_14    0.50
14         hr_13    0.49
31          hr_8    0.49
30          hr_7    0.49
29          hr_6    0.49
20         hr_19    0.49
19         hr_18    0.49
13         hr_12    0.49
11         hr_10    0.48
10          hr_1    0.48
32          hr_9    0.48
22         hr_20    0.48
23         hr_21    0.48
24         hr_22    0.48
25         hr_23    0.48
12         hr_11    0.48
28          hr_5    0.47
21          hr_2    0.46
27          hr_4    0.43
26          hr_3    0.43
9         mnth_7    0.23
5       season_3    0.19
7        mnth_11    0.17
34     weekday_6    0.16
8         mnth_6    0.15
37  weathersit_3    0.13
6       season_4    0.10
36  weathersit_2    0.07
4       season_2    0.04
35  workingday_1    0.04

In [22]:
x3=x2.drop(['temp'],axis=1)
vif_cal(x3,y1)

             Var    Vif
0          atemp  25.14
1            hum  14.73
2      windspeed   3.52
32     holiday_1   0.58
17         hr_17   0.50
16         hr_16   0.50
15         hr_15   0.50
14         hr_14   0.50
12         hr_12   0.49
29          hr_7   0.49
28          hr_6   0.49
13         hr_13   0.49
18         hr_18   0.49
11         hr_11   0.48
9           hr_1   0.48
31          hr_9   0.48
30          hr_8   0.48
19         hr_19   0.48
21         hr_20   0.48
22         hr_21   0.48
23         hr_22   0.48
24         hr_23   0.48
10         hr_10   0.48
27          hr_5   0.47
20          hr_2   0.46
26          hr_4   0.43
25          hr_3   0.43
8         mnth_7   0.23
6        mnth_11   0.17
4       season_3   0.17
33     weekday_6   0.16
7         mnth_6   0.15
36  weathersit_3   0.13
5       season_4   0.10
35  weathersit_2   0.07
3       season_2   0.04
34  workingday_1   0.04

In [23]:
x3['atemp']=(x2['atemp']**7)*10
x3['hum']=x2['hum']**5
x3['windspeed']=x2['windspeed']

In [24]:
x3.head()

,atemp,hum,windspeed,season_2,season_3,season_4,mnth_11,mnth_6,mnth_7,hr_1,...,hr_5,hr_6,hr_7,hr_8,hr_9,holiday_1,weekday_6,workingday_1,weathersit_2,weathersit_3
instant,,,,,,,,,,,,,,,,,,,,,
1,0.001639,0.348678,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,0.001121,0.327680,0.0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,0.001121,0.327680,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0.001639,0.237305,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5,0.001639,0.237305,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [25]:
vif_cal(x3,y1)
#After doing feature engineering now vif for all variables are low

             Var   Vif
2      windspeed  3.57
1            hum  2.78
0          atemp  2.43
32     holiday_1  0.57
15         hr_15  0.42
17         hr_17  0.42
16         hr_16  0.42
12         hr_12  0.42
13         hr_13  0.42
14         hr_14  0.42
31          hr_9  0.41
30          hr_8  0.41
29          hr_7  0.41
28          hr_6  0.41
19         hr_19  0.41
18         hr_18  0.41
11         hr_11  0.41
10         hr_10  0.41
9           hr_1  0.40
21         hr_20  0.40
22         hr_21  0.40
23         hr_22  0.40
24         hr_23  0.40
27          hr_5  0.39
20          hr_2  0.39
26          hr_4  0.36
25          hr_3  0.36
8         mnth_7  0.25
6        mnth_11  0.17
7         mnth_6  0.15
33     weekday_6  0.15
36  weathersit_3  0.15
4       season_3  0.10
5       season_4  0.08
35  weathersit_2  0.07
34  workingday_1  0.04
3       season_2  0.03

In [26]:
x3.columns

Index(['atemp', 'hum', 'windspeed', 'season_2', 'season_3', 'season_4',
       'mnth_11', 'mnth_6', 'mnth_7', 'hr_1', 'hr_10', 'hr_11', 'hr_12',
       'hr_13', 'hr_14', 'hr_15', 'hr_16', 'hr_17', 'hr_18', 'hr_19', 'hr_2',
       'hr_20', 'hr_21', 'hr_22', 'hr_23', 'hr_3', 'hr_4', 'hr_5', 'hr_6',
       'hr_7', 'hr_8', 'hr_9', 'holiday_1', 'weekday_6', 'workingday_1',
       'weathersit_2', 'weathersit_3'],
      dtype='object')

In [27]:
model(LinearRegression(),x3,y1)

The rmse score for the model= 116.17066947319256
---------------------------------------
The r^2 value for the model= 0.5960498692346222

In [28]:
m3 = sm.OLS(y1,sm.add_constant(x3),family=sm.families.Gaussian())
model3 = m3.fit()
model3.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                  Results: Ordinary least squares
====================================================================
Model:              OLS              Adj. R-squared:     0.603
Dependent Variable: cnt              AIC:                214083.3329
Date:               2019-05-27 17:35 BIC:                214378.3276
No. Observations:   17379            Log-Likelihood:     -1.0700e+05
Df Model:           37               F-statistic:        713.2
Df Residuals:       17341            Prob (F-statistic): 0.00
R-squared:          0.603            Scale:              13075.
--------------------------------------------------------------------
                  Coef.   Std.Err.    t     P>|t|   [0.025   0.975]
--------------------------------------------------------------------
const             -5.4549   5.2922  -1.0307 0.3027 -15.8282   4.9184
atemp             11.4902   2.3203   4.9521 0.0000   6.9422  16.0381
hum              -81.2752   4.9437 -16.4403 0.0000 -90.9653 -71.5851
windspeed        -38.6645   7.5735  -5.1053 0.0000 -53.5093 -23.8198
season_2          97.4198   2.6136  37.2738 0.0000  92.2968 102.5427
season_3         120.5882   3.0365  39.7129 0.0000 114.6363 126.5400
season_4         107.1492   2.8442  37.6733 0.0000 101.5743 112.7241
mnth_11          -38.6625   3.7402 -10.3371 0.0000 -45.9936 -31.3314
mnth_6            12.8126   3.4602   3.7028 0.0002   6.0302  19.5949
mnth_7           -16.8348   3.9306  -4.2830 0.0000 -24.5392  -9.1304
hr_1             -18.8908   6.0064  -3.1451 0.0017 -30.6639  -7.1177
hr_10            113.9050   6.0282  18.8953 0.0000 102.0891 125.7209
hr_11            144.6035   6.0491  23.9049 0.0000 132.7466 156.4603
hr_12            188.6604   6.0703  31.0793 0.0000 176.7621 200.5588
hr_13            187.6529   6.0821  30.8532 0.0000 175.7313 199.5745
hr_14            174.5962   6.0976  28.6337 0.0000 162.6443 186.5481
hr_15            185.2403   6.0984  30.3752 0.0000 173.2868 197.1938
hr_16            246.7223   6.0858  40.5407 0.0000 234.7935 258.6510
hr_17            397.9353   6.0728  65.5273 0.0000 386.0320 409.8386
hr_18            362.3924   6.0601  59.8001 0.0000 350.5141 374.2708
hr_19            249.3394   6.0352  41.3143 0.0000 237.5099 261.1690
hr_2             -28.5613   6.0270  -4.7389 0.0000 -40.3748 -16.7478
hr_20            166.0833   6.0204  27.5866 0.0000 154.2827 177.8840
hr_21            113.4625   6.0076  18.8864 0.0000 101.6869 125.2380
hr_22             74.2344   6.0017  12.3688 0.0000  62.4704  85.9985
hr_23             33.4051   5.9994   5.5681 0.0000  21.6457  45.1645
hr_3             -40.0270   6.0683  -6.5961 0.0000 -51.9214 -28.1325
hr_4             -43.5408   6.0723  -7.1704 0.0000 -55.4430 -31.6385
hr_5             -29.0590   6.0298  -4.8192 0.0000 -40.8780 -17.2399
hr_6              29.3218   6.0139   4.8757 0.0000  17.5340  41.1095
hr_7             164.9121   6.0040  27.4672 0.0000 153.1437 176.6804
hr_8             307.4925   6.0022  51.2298 0.0000 295.7276 319.2575
hr_9             163.7566   6.0115  27.2405 0.0000 151.9734 175.5398
holiday_1        -10.1262   5.6259  -1.7999 0.0719 -21.1536   0.9012
weekday_6         15.1210   3.2316   4.6791 0.0000   8.7867  21.4553
workingday_1      15.6448   2.5205   6.2071 0.0000  10.7044  20.5852
weathersit_2      -9.6982   2.1260  -4.5618 0.0000 -13.8653  -5.5311
weathersit_3     -66.2442   3.7016 -17.8962 0.0000 -73.4997 -58.9888
--------------------------------------------------------------------
Omnibus:             1890.058       Durbin-Watson:          0.402
Prob(Omnibus):       0.000          Jarque-Bera (JB):       3901.356
Skew:                0.693          Prob(JB):               0.000
Kurtosis:            4.862          Condition No.:          35
====================================================================

"""

### Random forest

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3,random_state=123)

rf=RandomForestRegressor()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
rmse=np.sqrt(mean_squared_error(y_test,y_pred))
rmse

70.52490292878376

In [51]:
#Tuning max depth
parameters = {'max_depth': range(1, 30)}
model_rf = GridSearchCV(RandomForestRegressor(),parameters, cv=5)
model_rf.fit(x_train, y_train)

print(model_rf.best_estimator_)
print(model_rf.score(x_train, y_train))

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=16,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)
0.9567683977033107

In [52]:
#Tuning max depth
parameters = {'max_features': range(1,11)}
model_rf = GridSearchCV(RandomForestRegressor(),parameters, cv=5)
model_rf.fit(x_train, y_train)

print(model_rf.best_estimator_)
print(model_rf.score(x_train, y_train))

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features=10, max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=None, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
0.9722892884557659

In [56]:
rf=RandomForestRegressor(max_depth=16,max_features=10,n_estimators=200)
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
rmse=np.sqrt(mean_squared_error(y_test,y_pred))
rmse

67.1434663360404

In [60]:
from sklearn import metrics

In [75]:
neg_scores=cross_val_score(rf,x_train,y_train,cv=10,scoring='neg_mean_squared_error')
scores=-1*neg_scores
rmse=np.sqrt(scores)

In [76]:
print(rmse.mean())

67.83612727522998